"""
Cocoa Intelligence Hub
CONFIDENCE + RISK ENGINE

This layer converts validated ensemble information into a transparent
decision-support index.

IMPORTANT:
- "confidence" here is an evidence/confidence INDEX, not a probability.
- It must not be interpreted as "X% chance the forecast is correct".
- No trading recommendation is generated by this module.
- A horizon is only scored when complete OOS metrics are available.
"""

from __future__ import annotations

from dataclasses import dataclass, asdict
from math import isfinite
from typing import Dict, Optional


TARGET = "ICCO-DAILY-USD"
UNIT = "USD/tonne"

LATEST_DATE = "2026-09-15"
LATEST_PRICE = 5972.24

# Latest ensemble output.
ENSEMBLE = {
    "30": {
        "forecast": 5947.65,
        "expected_change_pct": -0.41,
        "direction": "BEARISH",
        "range_low": 5895.90,
        "range_high": 5972.24,
        "spread": 76.34,
        "agreement": "MODEL_DISAGREEMENT",
    }
}

# Complete 30-trading-day OOS metrics currently available.
METRICS_30 = {
    "persistence": {"mae": 852.7946, "rmse": 1005.2209, "mape": 16.3897},
    "xgboost": {"mae": 702.9760, "rmse": 917.0740, "mape": 13.0905},
    "random_forest": {"mae": 770.7253, "rmse": 981.5077, "mape": 14.4840},
    "time_series": {"mae": 857.6410, "rmse": 1039.0324, "mape": 15.2945},
}

# Reference scale for the confidence index.
# This is deliberately a transparent engineering scale, not a market claim.
REFERENCE_MAPE = 20.0
REFERENCE_SPREAD_PCT = 5.0


@dataclass
class RiskResult:
    horizon: str
    status: str
    confidence_index: Optional[float]
    risk_level: str
    validation_score: Optional[float]
    agreement_score: Optional[float]
    dispersion_score: Optional[float]
    model_error_score: Optional[float]
    expected_change_pct: Optional[float]
    forecast_range: Optional[dict]
    notes: list


def clamp(value: float, low: float = 0.0, high: float = 100.0) -> float:
    return max(low, min(high, value))


def mean_mape(metrics: Dict[str, dict]) -> Optional[float]:
    values = [
        float(v["mape"])
        for v in metrics.values()
        if v.get("mape") is not None and isfinite(float(v["mape"]))
    ]
    return sum(values) / len(values) if values else None


def best_mape(metrics: Dict[str, dict]) -> Optional[float]:
    values = [
        float(v["mape"])
        for v in metrics.values()
        if v.get("mape") is not None and isfinite(float(v["mape"]))
    ]
    return min(values) if values else None


def agreement_score(agreement: str) -> float:
    # Agreement is evidence strength, not direction.
    return {
        "HIGH_BULLISH_AGREEMENT": 100.0,
        "HIGH_BEARISH_AGREEMENT": 100.0,
        "HIGH_NEUTRAL_AGREEMENT": 100.0,
        "PARTIAL_AGREEMENT": 65.0,
        "MODEL_DISAGREEMENT": 35.0,
        "UNKNOWN": 0.0,
    }.get(agreement, 0.0)


def dispersion_score(spread: float, current_price: float) -> float:
    if current_price <= 0:
        return 0.0

    spread_pct = abs(spread / current_price) * 100.0

    # 0% dispersion -> 100 score.
    # At or above the reference scale -> 0 score.
    return clamp(100.0 * (1.0 - spread_pct / REFERENCE_SPREAD_PCT))


def validation_score(metrics: Dict[str, dict]) -> float:
    """
    Score completeness and usefulness of the OOS validation evidence.

    Four complete models are required for the full score.
    This does not reward a model for merely having a low error.
    """
    required = {"mae", "rmse", "mape"}
    complete = 0

    for values in metrics.values():
        if required.issubset(values.keys()) and all(
            v is not None and isfinite(float(v)) and float(v) >= 0
            for v in values.values()
        ):
            complete += 1

    completeness = 100.0 * complete / 4.0
    return completeness


def model_error_score(metrics: Dict[str, dict]) -> float:
    """
    Convert average OOS MAPE into an evidence score.

    This is a bounded index. It is NOT accuracy probability.
    """
    avg = mean_mape(metrics)
    if avg is None:
        return 0.0

    return clamp(100.0 * (1.0 - avg / REFERENCE_MAPE))


def classify_risk(
    confidence: Optional[float],
    dispersion: Optional[float],
    agreement: str,
) -> str:
    if confidence is None:
        return "UNASSESSED"

    # High disagreement or wide forecast dispersion prevents a low-risk label.
    if agreement == "MODEL_DISAGREEMENT" or (dispersion is not None and dispersion < 50):
        return "HIGH"

    if confidence >= 75:
        return "LOW"
    if confidence >= 55:
        return "MODERATE"
    return "HIGH"


def build_30_day_result() -> RiskResult:
    ensemble = ENSEMBLE["30"]

    v_score = validation_score(METRICS_30)
    a_score = agreement_score(ensemble["agreement"])
    d_score = dispersion_score(
        ensemble["spread"],
        LATEST_PRICE,
    )
    e_score = model_error_score(METRICS_30)

    # Transparent weighting:
    # validation evidence 25%, model error 35%, agreement 25%, dispersion 15%.
    confidence = (
        0.25 * v_score
        + 0.35 * e_score
        + 0.25 * a_score
        + 0.15 * d_score
    )
    confidence = round(clamp(confidence), 2)

    notes = [
        "Confidence is an evidence index, not a probability.",
        "The ensemble direction is BEARISH, but model disagreement reduces confidence.",
        "The forecast spread is measured across the four model forecasts.",
        "OOS metrics are chronological and use the canonical ICCO-DAILY-USD target.",
        "This layer does not issue a buy, hold or sell recommendation.",
    ]

    return RiskResult(
        horizon="30-trading-days",
        status="READY",
        confidence_index=confidence,
        risk_level=classify_risk(
            confidence,
            d_score,
            ensemble["agreement"],
        ),
        validation_score=round(v_score, 2),
        agreement_score=round(a_score, 2),
        dispersion_score=round(d_score, 2),
        model_error_score=round(e_score, 2),
        expected_change_pct=ensemble["expected_change_pct"],
        forecast_range={
            "low": ensemble["range_low"],
            "high": ensemble["range_high"],
            "spread": ensemble["spread"],
        },
        notes=notes,
    )


def print_result(result: RiskResult) -> None:
    print("\n=== COCOA CONFIDENCE + RISK ENGINE ===")
    print(f"Target: {TARGET}")
    print(f"Latest observation: {LATEST_DATE}")
    print(f"Latest price: {LATEST_PRICE:.2f} {UNIT}")
    print(f"Horizon: {result.horizon}")
    print(f"Status: {result.status}")

    print("\n=== EVIDENCE SCORES ===")
    print(f"Validation evidence: {result.validation_score:.2f}/100")
    print(f"Model agreement:     {result.agreement_score:.2f}/100")
    print(f"Forecast dispersion: {result.dispersion_score:.2f}/100")
    print(f"OOS error evidence:  {result.model_error_score:.2f}/100")

    print("\n=== DECISION-INTELLIGENCE INDEX ===")
    print(f"Confidence index: {result.confidence_index:.2f}/100")
    print(f"Risk level: {result.risk_level}")

    print("\n=== FORECAST CONTEXT ===")
    print(f"Expected change: {result.expected_change_pct:+.2f}%")
    print(
        f"Range: {result.forecast_range['low']:.2f} - "
        f"{result.forecast_range['high']:.2f} {UNIT}"
    )
    print(f"Spread: {result.forecast_range['spread']:.2f} {UNIT}")

    print("\n=== INTERPRETATION ===")
    for note in result.notes:
        print(f"- {note}")

    print("\nCONFIDENCE + RISK ENGINE: PASSED")


def main() -> None:
    result = build_30_day_result()
    print_result(result)


if __name__ == "__main__":
    main()
